"""Regenerates protocol/vectors.json, the pose-mapping test vectors shared by the Python and C# tests."""
import json
import math
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rcsk.mapping import map_pose  # noqa: E402


def unit_q(rng):
    v = [rng.gauss(0, 1) for _ in range(4)]
    n = math.sqrt(sum(x * x for x in v))
    return [x / n for x in v]


def main():
    rng = random.Random(1998)  # the year Raccoon City fell
    cases = []
    for i in range(24):
        p = [rng.uniform(-50, 50), rng.uniform(-5, 20), rng.uniform(-50, 50)]
        q = unit_q(rng)
        origin = [rng.uniform(-50, 50), rng.uniform(-5, 5), rng.uniform(-50, 50)]
        anchor = [rng.uniform(-8000, 8000), rng.uniform(40, 200), rng.uniform(-8000, 8000)]
        heading = rng.uniform(-180, 180)
        scale = rng.choice([1.0, 1.0, 2.5, 0.5])
        flip = i % 3 != 2
        pos, rot = map_pose(p, q, origin, anchor, heading, scale, flip)
        cases.append({"p": p, "q": q, "origin": origin, "anchor": anchor, "heading": heading, "scale": scale, "flipZ": flip,
                      "pos": list(pos), "rot": list(rot)})
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "protocol", "vectors.json")
    with open(path, "w") as fh:
        json.dump({"note": "generated by tools/make_vectors.py", "cases": cases}, fh, indent=1)
    print(f"wrote {len(cases)} cases to {os.path.normpath(path)}")


if __name__ == "__main__":
    main()
